package pojos;
// Generated 2019-11-11 23:31:34 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import org.hibernate.annotations.CreationTimestamp;

/**
 * Historia generated by hbm2java
 */
@Entity
public class Historia  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy=GenerationType.SEQUENCE)
    private long id;
    @CreationTimestamp
    private Date kiedy;
    @OneToOne
    private My_user user;
    @OneToOne
    private Produkt produkt;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Date getKiedy() {
        return kiedy;
    }

    public void setKiedy(Date kiedy) {
        this.kiedy = kiedy;
    }

    public My_user getUser() {
        return user;
    }

    public void setUser(My_user user) {
        this.user = user;
    }

    public Produkt getProdukt() {
        return produkt;
    }

    public void setProdukt(Produkt produkt) {
        this.produkt = produkt;
    }


}


