package pojos;
// Generated 2019-11-11 23:31:34 by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;





/**
 * User generated by hbm2java
 */
@Entity
public class My_user implements Serializable   {

    @Id
    @GeneratedValue(strategy=GenerationType.SEQUENCE)
     private long userId;
     private String name;
     private String passwd;
     private int status;

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPasswd() {
        return passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
     

    


}


