package pojos;
// Generated 2019-11-11 23:31:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * Profil generated by hbm2java
 */
@Entity
public class Profil  implements java.io.Serializable {


      @Id
      @OneToOne
    private My_user id;
    private double kalorie;
    private double bialko;
    private double wegle;
    private double tluszcz;

    public My_user getId() {
        return id;
    }

    public void setId(My_user id) {
        this.id = id;
    }

   

    public double getKalorie() {
        return kalorie;
    }

    public void setKalorie(double kalorie) {
        this.kalorie = kalorie;
    }

    public double getBialko() {
        return bialko;
    }

    public void setBialko(double bialko) {
        this.bialko = bialko;
    }

    public double getWegle() {
        return wegle;
    }

    public void setWegle(double wegle) {
        this.wegle = wegle;
    }

    public double getTluszcz() {
        return tluszcz;
    }

    public void setTluszcz(double tluszcz) {
        this.tluszcz = tluszcz;
    }
    
    


}


